import "src/styles/globals.css";

import { appleGaramound, artega } from "@/styles/fonts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${artega.variable} ${appleGaramound.variable}`}>
      <body>{children}</body>
    </html>
  );
}
