import 'src/styles/globals.css';

import Footer from '@/components/ui/Footer';
import Navigation from '@/components/ui/Navigation';
import {
  appleGaramond,
  appleGaramondBold,
  appleGaramondLight,
  artega,
} from '@/styles/fonts';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${artega.variable} ${appleGaramond.variable} ${appleGaramondLight.variable} ${appleGaramondBold.variable} font-sans`}
    >
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
